# Running profile for Beans
spring:
  profiles:
    active: development
  application:
    name: springboot-aurelia-bootstrap

logging:
  config: src/main/resources/log4j2.properties

server:
  forceSslRedirect: false
  port: 8443

application:
  useDatabase: true